version: '2'

services:
  app:
    build: ./
    ports:
      - 8000:80
    volumes:
      - /dockerdata/nextcloud2/app:/var/www/html
      - /mnt/christpher_nextcloud:/data
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_PASSWORD
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - NEXTCLOUD_TRUSTED_DOMAINS
      - TRUSTED_PROXIES=app
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD
      - REDIS_HOST_PORT=6379
      - SMTP_HOST=smtp.sendgrid.net
      - SMTP_PORT=587
      - SMTP_AUTHTYPE=LOGIN
      - SMTP_NAME
      - SMTP_PASSWORD
      - MAIL_DOMAIN
      - SMTP_SECURE=tls
      - NEXTCLOUD_DATA_DIR=/data
  db:
    image: postgres
    ports: 
      - 5432:5432
    volumes:
      - /dockerdata/nextcloud2/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD
  redis:
    image: redis:latest
    restart: always
    ports:
      - 63790:6379
    command: >
          --requirepass ${REDIS_HOST_PASSWORD}
